### ISSUE TITLE
Replace icons with words

### ISSUE THREAD

**Issue by bre7** [Cellane/awesome-vapor#45]
Would you consider replacing Vapor2/Vapor3's icons with their alt text (v2/v3) ? Images aren't searchable 😞

**Comment by Cellane** [comment]
Hi! I’m not necessarily strictly against it, but I also don’t feel I should decide this on my own, so I’ll keep this issue open to gather some feedback from other users.

As for me, I wouldn’t want to prefer form over function, but at the same time I think most common use case for this list is “I need to do X with Vapor, let’s see if there’s some library that can help me” (in which case Vapor’s icons don’t prevent you from accomplishing your task), not “I want to see cool libraries for Vapor 2/Vapor 3” (in which case the icons could be problematic).

That being said, I’m leaning towards keeping the icons as they make the list visually interesting.

What do others think?

**Comment by Cellane** [comment]
Or, here’s a third option I just thought of.

What about having Travis trigger a script on each commit to the `master` branch that would go through the `README.md` file and filter all entries related to Vapor 2 into a separate Markdown file, then do the same for Vapor 3 entries and force push these two files into a new `generated` branch?

That solution would allow us up keep best of the both worlds.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Cellane** [comment]
Fixed in PRs #50, #51, #52, #53 and #54. The main `README.md` now contains links to automatically generated versions, filtered for Vapor 2 and Vapor 3.
