### ISSUE TITLE
 Hello, I recommend a Guardian Middleware for you to control API access times.

### ISSUE THREAD

**Issue by Jinxiansen** [Cellane/awesome-vapor#48]
This is the Guardian's address:

[https://github.com/Jinxiansen/Guardian](https://github.com/Jinxiansen/Guardian)

Thank you! ☺️

**Comment by Cellane** [comment]
That looks great, added! Thank you for the suggestion!

(We have the best library names, don’t we? Guardian is now sitting between Gatekeeper and Imperial entries, they all sound so… majestic 👑)

**Comment by Jinxiansen** [comment]
😘😘😘
