### ISSUE TITLE
Why Vapor2 is a requirement?

### ISSUE THREAD

**Issue by MihaelIsaev** [Cellane/awesome-vapor#66]
Hey,

I'm just wondering why Vapor2 is a requirement in `PULL_REQUEST_TEMPLATE.md`? 🙂

**Comment by Cellane** [comment]
Ha, that’s definitely a obsolete information at this point, an oversight. You can definitely open PR that changes the number from 2 to 3 😆

**Comment by Cellane** [comment]
By the way, I just realized I actually never meant it as a requirement. It was just to filter out Vapor 1.x projects, and it meant that anything that’s compatible with Vapor 2.x and 3.x is accepted.

**Comment by MihaelIsaev** [comment]
![Снимок экрана 2019-03-19 в 20 48 21](https://user-images.githubusercontent.com/1272610/54625266-614db100-4a88-11e9-9696-30e4736ff62b.jpg)
It's just my English then, my apologies, I translated it wrong 🙂
