### ISSUE TITLE
Vapor 4 content

### ISSUE THREAD

**Issue by imvm** [Cellane/awesome-vapor#78]
What do you think about starting to add links to content about Vapor 4? I saw that there are a couple of articles popping up about the beta.

**Comment by Cellane** [comment]
Definitely! It’ll require some adjustment in filtering, but let me see if I can make some progress on this today (or soon).

I think to make things easier for me, I may lock down new entries related to Vapor 2 finally. It’ll reach the end of life in November of this year anyhow.

**Comment by Cellane** [comment]
Tracking progress in #79.

**Comment by Cellane** [comment]
Implemented, thank you!

**Comment by imvm** [comment]
Awesome, thank you!!
